### ISSUE TITLE
Meta-tx community call 1 - Contract abi

### ISSUE THREAD

**Issue by pet3r-pan** [EthWorks/UniversalLoginSDK#110]
**Issue:** Hello, I have an issue in reaching you @marekkirejczyk 

***

Jk. Lol. I hope you don't mind this extremely intrusive and out of place github issue but I couldn't reach you anywhere else.

Alex van de sande raised an excellent suggestion of having you lead our next meta-tx community call around the contract abi standardisation 

We have got a few more teams uploading their code: https://github.com/Meta-tx/Harbour-MVP/tree/master/DEMOS

We were thinking of doing this meeting this tuesday on the 16th however if that is too short of a notice, lets do it thursday / friday?

Cheers,
Peter

**Comment by marekkirejczyk** [comment]
Hi @pet3r-pan,

I will be honored. 
You can reach me via email: marek@ethworks.io.

Thursday sounds excellent.

Marek
