### ISSUE TITLE
[IDEA] Keys that can only interact with one token type

### ISSUE THREAD

**Issue by Kyrrui** [EthWorks/UniversalLoginSDK#118]
In the name of security, I think it would be awesome to have keys that are limited to transferring only one type of token on an identity. This way, if a user has an identity and adds a key from this clicker example, that key can only use kilks. This way, even if a key from the clicker service becomes compromised, the other funds in the users identity are guaranteed safe.

**Comment by alexvandesande** [comment]
This will be possible with authorization contracts: https://github.com/EthWorks/UniversalLoginSDK/issues/88

**Comment by alexvandesande** [comment]
I'm closing this issue, as it's sort of a duplicate of that
