### ISSUE TITLE
When using new quick deploy option, ENS contracts do not deploy correctly.

### ISSUE THREAD

**Issue by Kyrrui** [EthWorks/UniversalLoginSDK#63]
When building with quick deploy option and trying to log in:
<img width="1446" alt="screen shot 2018-09-25 at 9 54 45 am" src="https://user-images.githubusercontent.com/8539426/46019115-5aca1800-c0a9-11e8-84fc-e176cc1d212e.png">

When doing manual deploy, works normally.

**Comment by marekkirejczyk** [comment]
Did you try to run `yarn` and `yarn build`?

**Comment by Kyrrui** [comment]
Yes, just tried again and received the same issue.
