### ISSUE TITLE
Not able to approve pending transaction

### ISSUE THREAD

**Issue by pranay01** [EthWorks/UniversalLoginSDK#70]
I run localhost:1234 on 2 browser clients in same machine. On one I create a user id, in other I try to login with the user id created in the first browser. I get pending authentication notification in the first browser - but I am not able to accept authentication. Attached is the browser console log

![screen shot 2018-09-28 at 9 38 04 am](https://user-images.githubusercontent.com/504541/46187722-97dd1700-c302-11e8-9a19-f99d68c1d667.jpg)
![screen shot 2018-09-28 at 9 37 57 am](https://user-images.githubusercontent.com/504541/46187723-97dd1700-c302-11e8-98b3-edd7dd3988b5.jpg)

**Comment by marekkirejczyk** [comment]
We can't reproduce. I propose following procedure:
Clean and do a full rebuild
```sh
./scripts/clean.sh
yarn
./scripts/travis.sh
```

Try running again (make sure you use new runner):
```sh
cd universal-login-example
yarn dev:start
```

And let us know if it worked.

**Comment by Kyrrui** [comment]
It has been over a week with no response by issuer, I will close for now
