### ISSUE TITLE
Parallelize Community Contributions

### ISSUE THREAD

**Issue by Kyrrui** [EthWorks/UniversalLoginSDK#73]
Hey @marekkirejczyk and @JustynaBroniszewska!

Currently I am focusing on a fork of this project full time. I would like to contribute back to the parent repo as much as possible, but I'm not sure what you guys are working on. If we could set up a quick community call to set up a task board or something similar then I could help you guys speed up progress towards your demo at Devcon4.

Cheers,
Kyle

**Comment by marekkirejczyk** [comment]
Hi @Kyrrui,

It is a great idea. 

I created a [board](https://github.com/EthWorks/UniversalLoginSDK/projects/1) and a first [task](https://github.com/EthWorks/UniversalLoginSDK/issues/76). More tasks are commin in following weeks.
I'll create more in the future. Please feel free to ask question :)

Marek
